# Generated by Django 5.1.3 on 2024-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
