# Generated by Django 5.1.3 on 2024-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_data_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news_data',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
