# Generated by Django 5.1.3 on 2024-11-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_news_data_content_alter_news_data_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_data',
            old_name='type',
            new_name='news_type',
        ),
    ]
