# Generated by Django 5.1.3 on 2024-11-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_type_news_data_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_data',
            old_name='news_type',
            new_name='type',
        ),
    ]
