# Generated by Django 5.1.3 on 2024-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_news_type_news_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_data',
            name='type',
        ),
        migrations.AddField(
            model_name='news_data',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('technology', 'Technology')], default='news', max_length=50),
        ),
    ]
