# Generated by Django 5.1.3 on 2024-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_news_data_type_news_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('technology', 'Technology'), ('economy', 'Economy')], default='news', max_length=50),
        ),
    ]
