# Generated by Django 5.1.3 on 2024-11-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_news_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
