# Generated by Django 5.1.3 on 2024-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_news_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='content',
            field=models.CharField(max_length=50000),
        ),
    ]
